security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $argon2id$v=19$m=65536,t=6,p=1$SesQQ0wQ4C9ctM814FYSwQ$ZovKVYZUmfl1a9ZvxF0yG0ykGJK3ObA5goYh4rHorJU # currently too lazy to actually make things safe
                        roles: 'ROLE_SUPER_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: auto
            cost: 10
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: admin_home
            logout:
                path: /admin/logout/
                target: /
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
